### ISSUE TITLE
open vpn is not running, what does it mean?

### ISSUE THREAD

**Issue by Genry777Morgan** [bhopkins0/OpenVPN-WebAdmin#2]

**Comment by bhopkins0** [comment]
This is likely an bug caused by updating to version 0.7.

You will need to SSH into the OpenVPN server and run the following commands:
```
wget -O /var/openvpn_scripts/status.sh https://raw.githubusercontent.com/bhopkins0/OpenVPN-Installer-For-Webadmin/main/status.sh
chmod +x /var/openvpn_scripts/status.sh
wget -O /var/openvpn_scripts/changeport.sh https://raw.githubusercontent.com/bhopkins0/OpenVPN-Installer-For-Webadmin/main/changeport.sh
chmod +x /var/openvpn_scripts/changeport.sh
```

This will add two new scripts that are required version 0.7.

If this does not work, please let me know

**Comment by Genry777Morgan** [comment]
All TAP-Windows adapters on this system are currently in use

**Comment by bhopkins0** [comment]
Can you provide a screenshot?
