### ISSUE TITLE
Will it be possible to connect from the same configuration file and from the phone and computer?

### ISSUE THREAD

**Issue by Genry777Morgan** [bhopkins0/OpenVPN-WebAdmin#4]

**Comment by bhopkins0** [comment]
While OpenVPN does support this (using `duplicate-cn`), I do not intend on adding this.

Requiring each device to have a unique configuration file makes it easier to manage.

You can generate configuration files with the webadmin. For version 0.7, this can be found under Client Manager.

![image](https://user-images.githubusercontent.com/91496127/162299442-5a39b3bc-b640-47be-9666-8948989d7063.png)
